# Generated by Django 3.2 on 2022-11-12 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralnotification',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='referralnotification',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
